### PR TITLE
Mac m1 is not jailbroken

### LINKED ISSUE #24: Detect jailbreak was wrong on mac M1
I have deploy my flutter app that using `flutter_jailbreak_detection` to detect jailbreak on Appstore. When I use my macbook M1 to install app it detect that my device is jailbreaked. 

Pls fix this issue :(

### PR DESCRIPTION
**Pull request by urielvexi**
fixes #24

### CODE REVIEW

**Comment by jeroentrappers** [comment]
Hi, this PR will not be merged into the main branch. 

For my purpose and semantics, MACs are not trusted platforms. People running apps on macs can have root access to the device and the security level is therefore less.

I propose to create your own fork of the library, or to create a parameter that is disabled by default to allow macs.

**Comment by tradegrub** [comment]
Can authors please merge this PR? I am not able to use this package due to this issue.

@jeroentrappers 
@urielvexi

**Comment by dgurudot** [comment]
Can authors please merge this PR? I am not able to use this package due to this issue.

@urielvexi 
@jeroentrappers

**Comment by jeroentrappers** [comment]
This change will not be merged into the main branch. It changes the semantics of the library. This should be implemented behind an optional flag, which is false by default. This means that M1 macs should be flagged as rooted by default, and with the new to be created flag, can optionally be allowed. You can also circumvent the rootcheck for arm macs in client code.

**Pull request closed without merging**
